Update patch set 2
Patch Set 2:

Btw, here are the errors from jenkins:

./utilities/file.py:3:1: E302 expected 2 blank lines, found 1
./langstroth/views.py:14:1: F811 redefinition of unused 'logging' from line 8
./langstroth/views.py:15:1: F401 'json' imported but unused
./langstroth/views.py:213:1: W391 blank line at end of file


Are you still having trouble accessing jenkins?

Patch-set: 2